<?php

namespace ElleOL\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends EntityRepository
{
	public function getLatestCount() {
		return $this->_em->createQueryBuilder()
			->select("s.saleCount")
			->from("EOLApiBundle:Sale", "s")
			->setMaxResults(1)
			->orderBy("s.createdAt", "desc")
			->getQuery()
			->getSingleScalarResult();
	}
}
